export const SAVE_AUTH = "SAVE_AUTH";

export const SAVE_AUTH_PENDING = "SAVE_AUTH_PENDING";

export const LOGIN_AUTH_STARTED = "LOGIN_AUTH_STARTED";

export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";

export const LOGIN_AUTH_FAILURE = "LOGIN_AUTH_FAILURE";

export const RESET_AUTH = "RESET_AUTH";