export const CREATE_CHECKOUT_PENDING = `CREATE_CHECKOUT_PENDING`;

export const CREATE_CHECKOUT_FULLFILLED = "CREATE_CHECKOUT_FULLFILLED";

export const CREATE_CHECKOUT_REJECTED = "CREATE_CHECKOUT_REJECTED";

export const RESET_CREATE_CHECKOUT = "RESET_CREATE_CHECKOUT";