export const CREATE_CUSTOMER_PENDING = `CREATE_CUSTOMER_PENDING`;

export const CREATE_CUSTOMER_FULLFILLED = "CREATE_CUSTOMER_FULLFILLED";

export const CREATE_CUSTOMER_REJECTED = "CREATE_CUSTOMER_REJECTED";

export const RESET_CREATE_CUSTOMER = "RESET_CREATE_CUSTOMER";