export const CREATE_ROOM_PENDING = `CREATE_ROOM_PENDING`;

export const CREATE_ROOM_FULLFILLED = "CREATE_ROOM_FULLFILLED";

export const CREATE_ROOM_REJECTED = "CREATE_ROOM_REJECTED";

export const RESET_CREATE_ROOM = "RESET_CREATE_ROOM";