export const CREATE_CHECKIN_PENDING = `CREATE_CHECKIN_PENDING`;

export const CREATE_CHECKIN_FULLFILLED = "CREATE_CHECKIN_FULLFILLED";

export const CREATE_CHECKIN_REJECTED = "CREATE_CHECKIN_REJECTED";

export const RESET_CREATE_CHECKIN = "RESET_CREATE_CHECKIN";