export const GET_CUSTOMER_PENDING = `GET_CUSTOMER_PENDING`;

export const GET_CUSTOMER_FULLFILLED = "GET_CUSTOMER_FULLFILLED";

export const GET_CUSTOMER_REJECTED = "GET_CUSTOMER_REJECTED";

export const RESET_GET_CUSTOMER = "RESET_GET_CUSTOMER";

export const ADD_CUSTOMER = "ADD_CUSTOMER";

export const EDIT_CUSTOMER = "EDIT_CUSTOMER";