export const GET_CHECKIN_PENDING = `GET_CHECKIN_PENDING`;

export const GET_CHECKIN_FULLFILLED = "GET_CHECKIN_FULLFILLED";

export const GET_CHECKIN_REJECTED = "GET_CHECKIN_REJECTED";

export const RESET_GET_CHECKIN = "RESET_GET_CHECKIN";

export const ADD_CHECKIN = "ADD_CHECKIN";

export const EDIT_CHECKIN = "EDIT_CHECKIN";