export const UPDATE_CUSTOMER_PENDING = `UPDATE_CUSTOMER_PENDING`;

export const UPDATE_CUSTOMER_FULLFILLED = "UPDATE_CUSTOMER_FULLFILLED";

export const UPDATE_CUSTOMER_REJECTED = "UPDATE_CUSTOMER_REJECTED";

export const RESET_UPDATE_CUSTOMER = "RESET_UPDATE_CUSTOMER";