export const UPDATE_ROOM_PENDING = `UPDATE_ROOM_PENDING`;

export const UPDATE_ROOM_FULLFILLED = "UPDATE_ROOM_FULLFILLED";

export const UPDATE_ROOM_REJECTED = "UPDATE_ROOM_REJECTED";

export const RESET_UPDATE_ROOM = "RESET_UPDATE_ROOM";